local Debugger = require("hotswitch-hs/lib/common/Debugger")
local Model = require("hotswitch-hs/lib/model/Model")
local KeyConstants = require("hotswitch-hs/lib/common/KeyConstants")

--[[
data format:

keyStatuses = {
    {
        app: "com.apple.Safari",
        key = "s",
        windowId = 123,
        window = hs.window object,
        isAutoGenerated = false,
    },
    {
        app: "com.apple.Safari",
        key = "f",
        windowId = 321,
        window = hs.window object,
        isAutoGenerated = false,
    },
    {
        app: "com.apple.mail",
        key = "m",
        windowId = 456,
        window = hs.window object,
        isAutoGenerated = false,
    },
    {
        app: "com.apple.iCal",
        key = "c",
        windowId = 789,
        window = hs.window object,
        isAutoGenerated = true,
    }
}
]]

-- Derive a hotkey key from an app name, avoiding keys already in usedKeys.
-- Returns nil when no derivation succeeds, so the caller can fall back to the static list.
-- Priority: first letter → first letter of second word → second uppercase letter (CamelCase)
local function deriveKeyFromAppName(appName, usedKeys)
    -- Strategy 1: first letter of the app name
    local firstLetter = appName:sub(1, 1):lower()
    if firstLetter:match("%a") and not usedKeys[firstLetter] then
        return firstLetter
    end

    -- Strategy 2: first letter of second word (multi-word names like "Google Chrome")
    local secondWordStart = appName:match("^%S+%s+(%S)")
    if secondWordStart then
        local secondLetter = secondWordStart:lower()
        if secondLetter:match("%a") and not usedKeys[secondLetter] then
            return secondLetter
        end
    end

    -- Strategy 3: second uppercase letter (CamelCase names like "iTerm2")
    local upperCount = 0
    for i = 1, #appName do
        local c = appName:sub(i, i)
        if c:match("%u") then
            upperCount = upperCount + 1
            if upperCount == 2 then
                local secondUpper = c:lower()
                if not usedKeys[secondUpper] then
                    return secondUpper
                end
                break
            end
        end
    end

    return nil
end

local KeyStatusModel = {}
KeyStatusModel.new = function(windowModel, settingModel)
    local obj = Model.new()

    obj.windowModel = windowModel
    obj.settingModel = settingModel

    obj.registeredKeyStatuses = {}
    obj.registeredAndAutoGeneratedKeyStatuses = {}

    obj.specifiedAutoGeneratedKeys = nil
    obj.autoGeneratedKeys = KeyConstants.DEFAULT_AUTO_GENERATED_KEYS

    obj.createKeyStatuses = function(self)
        local settings = self.settingModel.get()

        local windowIdBasedOrderedWindows = self.windowModel:getCreatedOrderedWindows()

        local registeredKeyStatuses = {}
        local registeredAndAutoGeneratedKeyStatuses = {}

        -- Pre-group registered keys by bundleID so multi-window apps consume them in order
        local registeredKeysByBundle = {}
        for _, setting in ipairs(settings) do
            if setting.app and #setting.keys > 0 then
                registeredKeysByBundle[setting.app] = {}
                for _, k in ipairs(setting.keys) do
                    table.insert(registeredKeysByBundle[setting.app], k)
                end
            end
        end

        local usedKeys = {}          -- key -> bundleID that claimed it
        local bundleDerivedKey = {}  -- bundleID -> derived key, shared across all windows of the same app
        local usedIndexOfAutoGeneratedKeys = 0

        for i = 1, #windowIdBasedOrderedWindows do
            local window = windowIdBasedOrderedWindows[i]

            local windowId = window:id()

            local bundleId = window:application():bundleID()
            local appName = window:application():name()

            local hasSettingKey = false
            local registeredKeys = registeredKeysByBundle[bundleId]
            if registeredKeys and #registeredKeys > 0 then
                hasSettingKey = true
                local key = table.remove(registeredKeys, 1)
                usedKeys[key] = bundleId

                local keyStatus = {
                    app = bundleId,
                    windowId = windowId,
                    key = key,
                    window = window,
                    isAutoGenerated = false,
                }

                table.insert(registeredKeyStatuses, keyStatus)
                table.insert(registeredAndAutoGeneratedKeyStatuses, keyStatus)
            end

            if hasSettingKey == false then
                local key

                -- All windows of the same app share one derived key
                if bundleDerivedKey[bundleId] then
                    key = bundleDerivedKey[bundleId]
                else
                    key = deriveKeyFromAppName(appName, usedKeys)
                    if key then
                        bundleDerivedKey[bundleId] = key
                    end
                end

                -- Fall back to static auto-generated list when derivation fails
                if key == nil then
                    while usedIndexOfAutoGeneratedKeys < #self.autoGeneratedKeys do
                        usedIndexOfAutoGeneratedKeys = usedIndexOfAutoGeneratedKeys + 1
                        local candidateKey = self.autoGeneratedKeys[usedIndexOfAutoGeneratedKeys]
                        if not usedKeys[candidateKey] then
                            key = candidateKey
                            break
                        end
                    end
                end

                if key then
                    usedKeys[key] = bundleId
                    table.insert(registeredAndAutoGeneratedKeyStatuses, {
                        app = bundleId,
                        windowId = windowId,
                        key = key,
                        window = window,
                        isAutoGenerated = true,
                    })
                end
            end
        end

        self.registeredKeyStatuses = registeredKeyStatuses
        self.registeredAndAutoGeneratedKeyStatuses = registeredAndAutoGeneratedKeyStatuses

        -- Sort by key for display
        table.sort(self.registeredAndAutoGeneratedKeyStatuses, function(a, b)
            return a.key:lower() < b.key:lower()
        end)
        self.sortedWindows = {}
        for _, ks in ipairs(self.registeredAndAutoGeneratedKeyStatuses) do
            table.insert(self.sortedWindows, ks.window)
        end
    end

    obj.resetAutoGeneratedKeys = function(self)
        local specifiedAutoGeneratedKeys
        if self.specifiedAutoGeneratedKeys ~= nil then
            specifiedAutoGeneratedKeys = self.specifiedAutoGeneratedKeys
        else
            specifiedAutoGeneratedKeys = KeyConstants.DEFAULT_AUTO_GENERATED_KEYS
        end

        local settings = self.settingModel.get()

        local allSettingKeys = {}
        for i, setting in ipairs(settings) do
            local keys = setting.keys
            for j, key in ipairs(keys) do
                table.insert(allSettingKeys, key)
            end
        end

        local autoGeneratedKeys = {}
        for i, specifiedAutoGeneratedKey in ipairs(specifiedAutoGeneratedKeys) do
            local hasSettingKey = false
            for j, settingKey in ipairs(allSettingKeys) do
                if settingKey == specifiedAutoGeneratedKey then
                    hasSettingKey = true
                    break
                end
            end
            if hasSettingKey == false then
               table.insert(autoGeneratedKeys, specifiedAutoGeneratedKey)
            end
        end

        self.autoGeneratedKeys = autoGeneratedKeys
    end

    obj.setSpecifiedAutoGeneratedKeys = function(self, specifiedAutoGeneratedKeys)
        self.specifiedAutoGeneratedKeys = specifiedAutoGeneratedKeys
    end

    return obj
end
return KeyStatusModel